### ISSUE TITLE
Non-fatal logging error in unit tests with k8s

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/elasticdl#1179]
Came across this logging error (non-fatal) in for unit tests with k8s ([example build](https://travis-ci.org/sql-machine-learning/elasticdl/jobs/584650771)):
```
docker run --rm -it --net=host -v $HOME/.kube:/root/.kube -v /home/$USER/.minikube/:/home/$USER/.minikube/ -v $(pwd):/work -w /work elasticdl:dev bash -c "make -f elasticdl/Makefile && K8S_TESTS=True pytest elasticdl/python/tests/k8s*.py"
```

```
1292[2019-09-13 15:40:57,125] [INFO] [k8s_worker_manager.py:120:_event_cb] Got event MODIFIED, phase Pending for pod: elasticdl-test-relaunch-worker-pod-1568389254-56-worker-2
1293--- Logging error ---
1294Traceback (most recent call last):
1295  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
1296    stream.write(msg)
1297  File "/usr/local/lib/python3.6/dist-packages/_pytest/capture.py", line 427, in write
1298    self.buffer.write(obj)
1299OSError: [Errno 9] Bad file descriptor
1300Call stack:
1301  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
1302    self._bootstrap_inner()
1303  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
1304    self.run()
1305  File "/usr/lib/python3.6/threading.py", line 864, in run
1306    self._target(*self._args, **self._kwargs)
1307  File "/work/elasticdl/python/common/k8s_client.py", line 75, in _watch
1308    self._event_cb(event)
1309  File "/work/elasticdl/python/master/k8s_worker_manager.py", line 120, in _event_cb
1310    "Got event %s, phase %s for pod: %s" % (evt_type, phase, pod_name)
1311Message: 'Got event DELETED, phase Pending for pod: elasticdl-test-relaunch-worker-pod-1568389254-56-worker-2'
1312Arguments: ()
1313The command "docker run --rm -it --net=host -v $HOME/.kube:/root/.kube -v /home/$USER/.minikube/:/home/$USER/.minikube/ -v $(pwd):/work -w /work elasticdl:dev bash -c "make -f elasticdl/Makefile && K8S_TESTS=True pytest elasticdl/python/tests/k8s*.py"" exited with 0.
```

**Comment by terrytangyuan** [comment]
This has been fixed
