### ISSUE TITLE
GO PS crashes when saving checkpoint 

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1812]
```
2020/03/10 10:10:13 PS service started at  11.235.160.158:2222
fatal error: concurrent map iteration and map write

goroutine 67282 [running]:
runtime.throw(0x95dd2d, 0x26)
    /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00064d5e0 sp=0xc00064d5b0 pc=0x42f6e2
runtime.mapiternext(0xc00064d6f0)
    /usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc00064d668 sp=0xc00064d5e0 pc=0x410c69
elasticdl.org/elasticdl/common.(*EmbeddingTable).ToIndexedSlices(0xc000130fc0, 0xc00018e4b0)
    /root/elasticdl/common/embedding_table.go:69 +0xfc fp=0xc00064d760 sp=0xc00064d668 pc=0x82166c
elasticdl.org/elasticdl/ps.(*Model).SaveToModelPB(0xc000104ca0, 0x17)
    /root/elasticdl/ps/model.go:86 +0x235 fp=0xc00064d908 sp=0xc00064d760 pc=0x8289d5
elasticdl.org/elasticdl/ps.SaveModelToCheckpoint(0xc0002910c0, 0x3a, 0xc000104ca0, 0x1, 0x3)
    /root/elasticdl/ps/checkpoint.go:125 +0x119 fp=0xc00064d9b0 sp=0xc00064d908 pc=0x827e99
elasticdl.org/elasticdl/ps.(*Server).saveCheckpointIfNeeded(0xc0000f7b80, 0x55f0)
    /root/elasticdl/ps/server.go:118 +0x1ca fp=0xc00064da48 sp=0xc00064d9b0 pc=0x82bcaa
elasticdl.org/elasticdl/ps.(*Server).PushGradients(0xc0000f7b80, 0x9fda40, 0xc001532a80, 0xc000116eb0, 0xc0000f7b80, 0xc001532a80, 0xc000381b30)
    /root/elasticdl/ps/server.go:174 +0x10c fp=0xc00064dad0 sp=0xc00064da48 pc=0x82c34c
elasticdl.org/elasticdl/proto._Pserver_PushGradients_Handler(0x901780, 0xc0000f7b80, 0x9fda40, 0xc001532a80, 0xc0014e11a0, 0x0, 0x9fda40, 0xc001532a80, 0xc0028f8000, 0x775fa)
    /root/elasticdl/proto/elasticdl.pb.go:1253 +0x217 fp=0xc00064db40 sp=0xc00064dad0 pc=0x820367
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000df080, 0xa01dc0, 0xc00025e480, 0xc00022e500, 0xc00018eb10, 0xeea280, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4 fp=0xc00064de18 sp=0xc00064db40 pc=0x804b34
google.golang.org/grpc.(*Server).handleStream(0xc0000df080, 0xa01dc0, 0xc00025e480, 0xc00022e500, 0x0)
    /root/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97 fp=0xc00064df48 sp=0xc00064de18 pc=0x808857
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002c1e4, 0xc0000df080, 0xa01dc0, 0xc00025e480, 0xc00022e500)
    /root/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb fp=0xc00064dfb8 sp=0xc00064df48 pc=0x81590b
runtime.goexit()
```

**Comment by skydoorkai** [comment]
Need an RWLock for EmbeddingTables iteration in SaveToModelPB.
