### ISSUE TITLE
Worker pod crashes when Go PS is used

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1826]
```
[2020-03-12 08:55:32,559] [INFO] [model_handler.py:312:_clone_function] Replace embedding layer with elasticdl.layers.Embedding
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elasticdl/elasticdl/python/worker/main.py", line 44, in <module>
    main()
  File "/elasticdl/elasticdl/python/worker/main.py", line 40, in main
    worker.run()
  File "/elasticdl/elasticdl/python/worker/worker.py", line 1143, in run
    self._train_and_evaluate()
  File "/elasticdl/elasticdl/python/worker/worker.py", line 1085, in _train_and_evaluate
    self._process_train_end_callback_task_if_needed()
  File "/elasticdl/elasticdl/python/worker/worker.py", line 968, in _process_train_end_callback_task_if_needed
    self._callbacks_list.on_train_end()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 379, in on_train_end
    callback.on_train_end(logs)
  File "/elasticdl/elasticdl/python/elasticdl/callbacks.py", line 46, in on_train_end
    self.model, dataset
  File "/elasticdl/elasticdl/python/common/model_handler.py", line 227, in get_model_to_export
    trained_params = _get_trained_params_from_checkpoint(checkpoint_dir)
  File "/elasticdl/elasticdl/python/common/model_handler.py", line 21, in _get_trained_params_from_checkpoint
    checkpoint_dir, 0, 1
  File "/elasticdl/elasticdl/python/common/save_utils.py", line 240, in restore_params_from_checkpoint
    "The versions in model shards are not consistency"
```

**Comment by QiJune** [comment]
I find the root cause:

In python PS:

https://github.com/sql-machine-learning/elasticdl/blob/be22bb5790e5e6d6e1cd7dd4cf5819b7276f1464/elasticdl/python/ps/servicer.py#L142-L145

save checkpoint is protected by the verson lock.

In Go PS:

https://github.com/sql-machine-learning/elasticdl/blob/be22bb5790e5e6d6e1cd7dd4cf5819b7276f1464/elasticdl/pkg/ps/server.go#L182-L186

save checkpoint is not protected by the version lock.

So the checkpoint version saved by Go PS is not consistent strictly.

**Comment by workingloong** [comment]
> I find the root cause:
> 
> In python PS:
> 
> https://github.com/sql-machine-learning/elasticdl/blob/be22bb5790e5e6d6e1cd7dd4cf5819b7276f1464/elasticdl/python/ps/servicer.py#L142-L145
> 
> save checkpoint is protected by the verson lock.
> 
> In Go PS:
> 
> https://github.com/sql-machine-learning/elasticdl/blob/be22bb5790e5e6d6e1cd7dd4cf5819b7276f1464/elasticdl/pkg/ps/server.go#L182-L186
> 
> save checkpoint is not protected by the version lock.
> 
> So the checkpoint version saved by Go PS is not consistent strictly.

It may be reasonable that the model versions for shards in checkpoint keep consistency
