### ISSUE TITLE
worker pod crashes when get task

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1829]
```
2020-03-12 22:03:32.300671: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elasticdl/python/worker/main.py", line 44, in <module>
    main()
  File "/elasticdl/python/worker/main.py", line 40, in main
    worker.run()
  File "/elasticdl/python/worker/worker.py", line 1144, in run
    self._train_and_evaluate()
  File "/elasticdl/python/worker/worker.py", line 1074, in _train_and_evaluate
    self._minibatch_size, err_msg
  File "/elasticdl/python/worker/task_data_service.py", line 86, in report_record_done
    task = self._pending_tasks[0]
IndexError: deque index out of range
```

**Comment by QiJune** [comment]
It seems that timeout mechanisim does not worker too. I will debug this.

**Comment by QiJune** [comment]
I describe the pod:

```
Status:       Failed
State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 12 Mar 2020 17:07:32 +0800
      Finished:     Fri, 13 Mar 2020 06:04:06 +0800
```
The exit code is 1.


And the master pod log:

```
   for event in stream:
[2020-03-13 01:58:50,535] [INFO] [k8s_instance_manager.py:233:_event_cb] Got event ADDED, phase Running for pod: elasticdl-test-edl-dban-qitian910-worker-1
[2020-03-13 01:58:50,538] [INFO] [k8s_instance_manager.py:233:_event_cb] Got event ADDED, phase Failed for pod: elasticdl-test-edl-dban-qitian910-worker-6
[2020-03-13 01:58:50,540] [INFO] [k8s_instance_manager.py:233:_event_cb] Got event ADDED, phase Running for pod: elasticdl-test-edl-dban-qitian910-ps-2
```

The master find the failed pod.

It seems that we only handle exit_code 137

https://github.com/sql-machine-learning/elasticdl/blob/d002f4a49127a16a38955340bc2711606913f7c0/elasticdl/python/master/k8s_instance_manager.py#L251-L259

So this failed worker pod is not handled.
