### ISSUE TITLE
Crash in ftlib calls with error `root:'list' object has no attribute parameters`

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1883]
If worker pods can come to live at similar time to bypass #1882 , they will hit another error `ERROR:root:'list' object has no attribute parameters` in ftlib calls.

```
joining with ips:
11.234.173.7
[2020-03-30 06:03:02,886] [WARNING] [model_handler.py:185:get_model_handler] Allreduce distribution strategy is not supported yet. Switching to use the default distribution strategy.
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,762] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,762] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,762] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,764] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,764] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,764] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,765] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,765] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,765] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,766] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,766] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,766] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,777] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,777] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,777] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
ERROR:root:'list' object has no attribute 'parameters'
[2020-03-30 06:03:35,777] [WARNING] [worker.py:762:_broadcast_model_params] Failed to perform barrier operation
[2020-03-30 06:03:35,777] [WARNING] [worker.py:814:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-30 06:03:35,777] [WARNING] [worker.py:837:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
2020-03-30 06:03:35.778527: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
Traceback (most recent call last):
  File "/elasticdl/elasticdl/python/worker/worker.py", line 982, in _process_minibatch_and_report
    train_with_local_model,
  File "/elasticdl/elasticdl/python/worker/worker.py", line 889, in _process_minibatch
    features, labels
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elasticdl/elasticdl/python/worker/main.py", line 76, in <module>
    main()
  File "/elasticdl/elasticdl/python/worker/main.py", line 72, in main
    worker.run()
  File "/elasticdl/elasticdl/python/worker/worker.py", line 1133, in run
    self._train_and_evaluate()
  File "/elasticdl/elasticdl/python/worker/worker.py", line 1052, in _train_and_evaluate
    train_with_local_model,
  File "/elasticdl/elasticdl/python/worker/worker.py", line 990, in _process_minibatch_and_report
    raise ex
  File "/elasticdl/elasticdl/python/worker/worker.py", line 982, in _process_minibatch_and_report
    train_with_local_model,
  File "/elasticdl/elasticdl/python/worker/worker.py", line 889, in _process_minibatch
    features, labels
TypeError: 'NoneType' object is not iterable

```

**Comment by skydoorkai** [comment]
This is because of that ElasticDL passes a list of grads to [wait_gradients_ready](https://github.com/sql-machine-learning/elasticdl/blob/760013c66b80c45628af411e6af7d8eaf6833914/elasticdl/python/collective_ops/communicator.py#L59),  but  the corresponding [API in ftlib](https://github.com/caicloud/ftlib/blob/7ba2dbf920b2bdcc89ff84e10bb3088a915594b7/ftlib/commlib/pytorch/impl.py#L36 ) requires a format of a model with parameters.

**Comment by skydoorkai** [comment]
With some fix, now the error is:

```
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
[2020-03-31 12:18:22,565] [WARNING] [communicator.py:66:allreduce] allreduce result is CommLibStatus.SUCCESS
[2020-03-31 12:18:22,566] [WARNING] [worker.py:761:_broadcast_model_params] Failed to perform barrier operation
[2020-03-31 12:18:22,567] [WARNING] [worker.py:813:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-31 12:18:22,567] [WARNING] [worker.py:836:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
[2020-03-31 12:18:22,573] [WARNING] [communicator.py:66:allreduce] allreduce result is CommLibStatus.SUCCESS
[2020-03-31 12:18:22,574] [WARNING] [worker.py:761:_broadcast_model_params] Failed to perform barrier operation
[2020-03-31 12:18:22,574] [WARNING] [worker.py:813:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-03-31 12:18:22,574] [WARNING] [worker.py:836:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
[2020-03-31 12:18:22,579] [WARNING] [communicator.py:66:allreduce] allreduce result is CommLibStatus.SUCCESS
[2020-03-31 12:18:22,580] [WARNING] [worker.py:761:_broadcast_model_params] Failed to perform barrier operation
[2020-03-31 12:18:22,580] [WARNING] [worker.py:813:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
```

**Comment by skydoorkai** [comment]
Fixed with new FTLib API return values. #1888
