### ISSUE TITLE
Avoid hang in Allreduce training

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1895]
If data is distributed unevenly among workers, some workers may have consumed all their data before other workers. This will cause `allreduce` op hang.

One solution is to quit the workers that have already finished training, so FTLib can get a new consensus.

**Comment by skydoorkai** [comment]
worker 0 has no tasks

```
[2020-07-15 06:29:15,255] [INFO] [task_data_service.py:220:_gen] No tasks for now, maybe more later
[2020-07-15 06:29:20,302] [INFO] [task_data_service.py:220:_gen] No tasks for now, maybe more later
[2020-07-15 06:29:25,349] [INFO] [task_data_service.py:220:_gen] No tasks for now, maybe more later
[2020-07-15 06:29:30,395] [INFO] [task_data_service.py:220:_gen] No tasks for now, maybe more later
[2020-07-15 06:29:35,441] [INFO] [task_data_service.py:220:_gen] No tasks for now, maybe more later
```

worker 1 fails as worker 0 does not have tasks to do

```
ERROR:root:[/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 60000ms for recv operation to complete
ERROR:root:Application timeout caused pair closure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 364, in func
    result = ops(*argc, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ftlib/commlib/pytorch/impl.py", line 72, in barrier
    dist.barrier()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1496, in barrier
    work.wait()
RuntimeError: Application timeout caused pair closure
[2020-07-15 06:30:15,492] [WARNING] [worker.py:771:_broadcast_model_params] Failed to perform barrier operation
[2020-07-15 06:30:15,492] [WARNING] [worker.py:817:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-07-15 06:30:15,492] [WARNING] [worker.py:840:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort
[2020-07-15 06:32:55,593] [WARNING] [worker.py:771:_broadcast_model_params] Failed to perform barrier operation
[2020-07-15 06:32:55,593] [WARNING] [worker.py:817:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-07-15 06:32:55,593] [WARNING] [worker.py:840:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort
[2020-07-15 06:35:14,858] [WARNING] [worker.py:771:_broadcast_model_params] Failed to perform barrier operation
[2020-07-15 06:35:14,859] [WARNING] [worker.py:817:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-07-15 06:35:14,859] [WARNING] [worker.py:840:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort
WARNING:root:Connection reset by peer
WARNING:root:rebuild process returns abort
[2020-07-15 06:36:53,060] [WARNING] [worker.py:771:_broadcast_model_params] Failed to perform barrier operation
[2020-07-15 06:36:53,060] [WARNING] [worker.py:817:_collect_gradients_with_allreduce_robust] Failed to broadcast model parameters
[2020-07-15 06:36:53,060] [WARNING] [worker.py:840:_run_training_task] Failed to perform allreduce operation onthe gradients. Retrying...
WARNING:root:Socket Timeout
WARNING:root:rebuild process returns abort

```
