### ISSUE TITLE
Fix pre-commit check error

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/elasticdl#1969]
We cannot use `*` in the following code snippet

https://github.com/sql-machine-learning/elasticdl/blob/3593b9cc197455423e6b2c3b72dfe29b3e80be77/elasticdl/python/common/k8s_client.py#L51-L61

Currently, the seed isort rule in `.pre-commit-hook` complains the following

```text
seed isort known_third_party.............................................Failed
hookid: seed-isort-config

Traceback (most recent call last):
  File "/Users/yi/.cache/pre-commit/repoCkImBV/py_env-python2.7/bin/seed-isort-config", line 11, in <module>
    load_entry_point('seed-isort-config==1.9.1', 'console_scripts', 'seed-isort-config')()
  File "/Users/yi/.cache/pre-commit/repoCkImBV/py_env-python2.7/lib/python2.7/site-packages/seed_isort_config.py", line 103, in main
    third_party = third_party_imports(filenames, appdirs)
  File "/Users/yi/.cache/pre-commit/repoCkImBV/py_env-python2.7/lib/python2.7/site-packages/seed_isort_config.py", line 54, in third_party_imports
    visitor.visit(ast.parse(f.read(), filename=filename))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "elasticdl/python/common/k8s_client.py", line 54
    *,
     ^
SyntaxError: invalid syntax
```

**Comment by wangkuiyi** [comment]
Thanks to @terrytangyuan  -- this is not bug; it is due to my pre-commit is working with Python 2.7, and I should use Python 3.

I corrected my local setting by reinstalling pre-commit with Python 3 explicitly.

```bash
pip uninstall pre-commit
python3 -m pip install pre-commit
```
