### ISSUE TITLE
Support reliable worker pod detection for allreduce

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#2174]
In worker.py, it sleeps for 20 seconds, hoping that is enough for FTLib consensus service to detect worker pod.
This is not reliable and fails often.

```
    if args.distribution_strategy == DistributionStrategy.ALLREDUCE:
        logger.info(
            "Wait for %s seconds for FTLib consensus service to "
            "detect the worker pod" % str(_ALLREDUCE_STRATEGY_WARM_UP_SECS)
        )
        time.sleep(_ALLREDUCE_STRATEGY_WARM_UP_SECS)
```

**Comment by skydoorkai** [comment]
Currently, workers always crash because of this issue.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/main.py", line 89, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/main.py", line 83, in main
    set_parallelism=True,
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/worker.py", line 135, in __init__
    self._init_from_args(args)
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/worker.py", line 174, in _init_from_args
    if self._distribution_strategy == DistributionStrategy.ALLREDUCE
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/collective_ops/communicator.py", line 40, in __init__
    peer_list = list(self._get_peer_set(service_name))
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/collective_ops/communicator.py", line 142, in _get_peer_set
    temp_set = socket.getaddrinfo(svc_name, 0, proto=socket.IPPROTO_TCP)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```
