### ISSUE TITLE
FTlib consensus is unreliable and slow, we should use master to do the consensus.

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#2192]

**Comment by skydoorkai** [comment]
FTlib has two main components: consensus and communicator (init process group, broadcast, allreduce, barrier, etc).
In order to use the master for consensus implementation, we need to write similar two components in ElasticDL.

**Comment by skydoorkai** [comment]
Tested with CIFAR10 training with 3 workers, the consensus is quite slow(30s or more) and occasionally fails.

The command to submit the job:
```
elasticdl train \
        --image_name=${your_image_hub}/elasticdl:allreduce \
 		  --model_zoo=/model_zoo \
 		  --model_def=cifar10_functional_api.cifar10_functional_api.custom_model \
 		  --training_data=/testdata/elasticdl/cifar10/train \
 		  --validation_data=/testdata/elasticdl/cifar10/test \
 		  --num_epochs=1 \
 		  --master_resource_request="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
 		  --master_resource_limit="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
 		  --worker_resource_request="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
 		  --worker_resource_limit="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
 		  --minibatch_size=64 \
 		  --num_minibatches_per_task=8 \
 		  --num_workers=3 \
 		  --job_name=edl-allreduce-test \
 		  --image_pull_policy=Always \
 		  --distribution_strategy=AllreduceStrategy \
                  --volume='claim_name=your_data_volume,mount_path=/testdata' 
```

Occasional failure:

```
 3742 Traceback (most recent call last):
 3743   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
 3744     "__main__", mod_spec)
 3745   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
 3746     exec(code, run_globals)
 3747   File "/elasticdl/python/worker/main.py", line 89, in <module>
 3748     main()
 3749   File "/elasticdl/python/worker/main.py", line 83, in main
 3750     set_parallelism=True,
 3751   File "/elasticdl/python/worker/worker.py", line 135, in __init__
 3752     self._init_from_args(args)
 3753   File "/elasticdl/python/worker/worker.py", line 174, in _init_from_args
 3754     if self._distribution_strategy == DistributionStrategy.ALLREDUCE
 3755   File "/elasticdl/python/collective_ops/communicator.py", line 40, in __init__
 3756     peer_list = list(self._get_peer_set(service_name))
 3757   File "/elasticdl/python/collective_ops/communicator.py", line 142, in _get_peer_set
 3758     temp_set = socket.getaddrinfo(svc_name, 0, proto=socket.IPPROTO_TCP)
 3759   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
 3760     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
 3761 socket.gaierror: [Errno -2] Name or service not known
```

**Comment by workingloong** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/main.py", line 79, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/main.py", line 73, in main
    set_parallelism=True,
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/worker.py", line 120, in __init__
    self._init_from_args(args)
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/worker/worker.py", line 160, in _init_from_args
    if self._distribution_strategy == DistributionStrategy.ALLREDUCE
  File "/usr/local/lib/python3.6/dist-packages/elasticdl/python/collective_ops/communicator.py", line 78, in __init__
    socket.gethostname()
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 100, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/ftlib/impl.py", line 308, in build
    raise Exception("building consensus failed")
Exception: building consensus failed
```

**Comment by workingloong** [comment]
We have used RendezvousServer on the master to build the communication group for Horovod. So, we can close the issue.
